model_name_or_path: /content/SDAR_Work/SDAR/training/model/SDAR-8B-Chat
train_from_scratch: false
trust_remote_code: true
quantization_bit: 4
quantization_method: bib
double_quantization: false
use_apollo: true
apollo_layerwise: true  # choices: [true, false], use false for DDP training
apollo_target: all
apollo_rank: 128
apollo_scale: 32.0
apollo_scale_type: channel
stage: dpo
pref_beta: 0.1
pref_loss: simpo
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all
freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_language_model: true
deepspeed: /content/SDAR_Work/SDAR/training/llama_factory_sdar/examples/deepspeed/ds_z2_offload_config.json
gradient_checkpointing: true
dataset: lyrical_v5_ru_en_dpo_orpo
use_rslora: true
lora_bias: lora_only
template: qwen3
block_length: 4
cutoff_len: 2048
truncate_mode: drop
overwrite_cache: false
tokenized_path: /content/drive/MyDrive/LyricalSDAR_8borpo/cache
preprocessing_num_workers: 96
dataloader_num_workers: 4
neat_packing: true
output_dir: /content/drive/MyDrive/LyricalSDAR_8borpo
logging_steps: 5
save_steps: 400
save_total_limit: 8
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
run_name: sdar_8b_lyrical
include_effective_tokens_per_second: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-05
num_train_epochs: 21.0
lr_scheduler_type: cosine
warmup_ratio: 0.04
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
